name: google_maps_routes_api
description: Google Maps Routes API service to calculate routes and route matrixes between locations.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  http: ^0.13.5
